const char *schema_sqlstr =
"--\n"
"-- scrap500.schema.sqlite3.sql\n"
"--\n"
"\n"
"pragma foreign_keys = on;\n"
"\n"
"begin transaction;\n"
"\n"
"drop table if exists site;\n"
"drop table if exists system;\n"
"drop table if exists sysattr_name;\n"
"drop table if exists sysattr_val;\n"
"drop table if exists top500;\n"
"\n"
"-- [table] site\n"
"create table site (\n"
"    id integer primary key not null,\n"
"    site_id integer not null,\n"
"    name text,\n"
"    url text,\n"
"    segment text,\n"
"    city text,\n"
"    country text,\n"
"    unique(site_id)\n"
");\n"
"\n"
"-- [table] system\n"
"create table system (\n"
"    id integer primary key not null,\n"
"    system_id integer not null,\n"
"    name text not null,\n"
"    summary text,\n"
"    manufacturer text,\n"
"    url text,\n"
"    unique(system_id)\n"
");\n"
"\n"
"-- [table] sysattr_name\n"
"create table sysattr_name (\n"
"    id integer primary key not null,\n"
"    name text not null,\n"
"    unique(name)\n"
");\n"
"\n"
"insert into sysattr_name(id, name) values (1, 'Cores');\n"
"insert into sysattr_name(id, name) values (2, 'Memory');\n"
"insert into sysattr_name(id, name) values (3, 'Processor');\n"
"insert into sysattr_name(id, name) values (4, 'Interconnect');\n"
"insert into sysattr_name(id, name) values (5, 'Linpack Performance (Rmax)');\n"
"insert into sysattr_name(id, name) values (6, 'Theoretical Peak (Rpeak)');\n"
"insert into sysattr_name(id, name) values (7, 'Nmax');\n"
"insert into sysattr_name(id, name) values (8, 'Nhalf');\n"
"insert into sysattr_name(id, name) values (9, 'HPCG [TFlop/s]');\n"
"insert into sysattr_name(id, name) values (10, 'Power');\n"
"insert into sysattr_name(id, name) values (11, 'Power Measurement Level');\n"
"insert into sysattr_name(id, name) values (12, 'Measured Cores');\n"
"insert into sysattr_name(id, name) values (13, 'Operating System');\n"
"insert into sysattr_name(id, name) values (14, 'Compiler');\n"
"insert into sysattr_name(id, name) values (15, 'Math Library');\n"
"insert into sysattr_name(id, name) values (16, 'MPI');\n"
"\n"
"-- [table] sysattr_val\n"
"create table sysattr_val (\n"
"    id integer primary key not null,\n"
"    nid integer not null references sysattr_name(id),\n"
"    sval text,          -- text value or unit for rval\n"
"    rval real,\n"
"    unique(id, nid)\n"
");\n"
"\n"
"-- [table] top500\n"
"create table top500 (\n"
"    id integer primary key not null,\n"
"    time integer not null,\n"
"    rank integer not null,\n"
"    system_id integer not null references system(system_id),\n"
"    site_id integer not null references site(site_id),\n"
"    unique(time, rank, system_id)   -- there exist ties in rank\n"
");\n"
"\n"
"end transaction;\n"
"\n"
;
